[project]
name = "software-tran"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.15.1",
    "dotenv>=0.9.9",
    "greenlet>=3.1.1",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.39",
]
